# Generated by Django 5.2.8 on 2026-01-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('user_agent', models.CharField(blank=True, default='Chrome', max_length=30, null=True)),
                ('payload', models.CharField(blank=True, max_length=20, null=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
