# Generated by Django 5.2.8 on 2026-01-14 19:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='last_activity',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user_id',
        ),
        migrations.AddField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='token_hash',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_agent',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['token_hash', 'expires_at'], name='sessions_token_h_9f69fc_idx'),
        ),
        migrations.AlterModelTable(
            name='session',
            table='sessions',
        ),
    ]
