# Generated by Django 5.2.8 on 2026-01-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_last_login_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(default='127.0.0.1', max_length=50),
        ),
    ]
